[package]
name = "event_sourcing"
version = "0.1.0"
description = "TBD"
repository = "https://github.com/bayov/event_sourcing"
readme = "README.md"
license = "PRIVATE"
edition = "2021"
keywords = ["event", "event-sourcing"]
categories = ["data-structures"]

[dependencies]
chrono = "0.4.31"
derive_more = { version = "1.0.0-beta.6", features = ["display", "index"] }
futures = "0.3.29"
